android_resource(
  name = 'res',
  res = 'res',
  package = 'com.facebook.buck.demo',
  visibility = [
    '//android/java/com/facebook/buck/demo:lib',
  ],
)

project_config(
  src_target = ':res'
)
