android_library(
  name = 'lib',
  srcs = glob(['*.java']),
  deps = [
    '//android/resources:res',
    '//android/cxx:jni',
  ],
  visibility = [
    '//android:demo-app',
  ],
)

project_config(
  src_target = ':lib',
)
