cxx_library(
  name = 'jni',
  srcs = glob(['*.cpp']),
  deps = [
    '//common:hello',
  ],
  visibility = [
    '//android/java/com/facebook/buck/demo:lib',
  ],
)

project_config(
  src_target = ':jni'
)
