cxx_library(
  name = 'jni',
  srcs = glob(['*.cpp']),
  soname = 'libjni.so',
  compiler_flags = [
    '-fvisibility=hidden',
  ],
  deps = [
    '//common:hello',
  ],
  visibility = [
    '//android/java/com/facebook/buck/demo:lib',
  ],
)

project_config(
  src_target = ':jni'
)
